// Country to flag emoji mapping
const countryFlags: Record<string, string> = {
  "Afghanistan": "🇦🇫",
  "Albania": "🇦🇱",
  "Algeria": "🇩🇿",
  "Andorra": "🇦🇩",
  "Angola": "🇦🇴",
  "Antigua and Barbuda": "🇦🇬",
  "Argentina": "🇦🇷",
  "Armenia": "🇦🇲",
  "Australia": "🇦🇺",
  "Austria": "🇦🇹",
  "Azerbaijan": "🇦🇿",
  "Bahamas": "🇧🇸",
  "Bahrain": "🇧🇭",
  "Bangladesh": "🇧🇩",
  "Barbados": "🇧🇧",
  "Belarus": "🇧🇾",
  "Belgium": "🇧🇪",
  "Belize": "🇧🇿",
  "Benin": "🇧🇯",
  "Bhutan": "🇧🇹",
  "Bolivia": "🇧🇴",
  "Bosnia and Herzegovina": "🇧🇦",
  "Botswana": "🇧🇼",
  "Brazil": "🇧🇷",
  "Brunei": "🇧🇳",
  "Bulgaria": "🇧🇬",
  "Burkina Faso": "🇧🇫",
  "Burundi": "🇧🇮",
  "Cambodia": "🇰🇭",
  "Cameroon": "🇨🇲",
  "Canada": "🇨🇦",
  "Cape Verde": "🇨🇻",
  "Central African Republic": "🇨🇫",
  "Chad": "🇹🇩",
  "Chile": "🇨🇱",
  "China": "🇨🇳",
  "Colombia": "🇨🇴",
  "Comoros": "🇰🇲",
  "Congo": "🇨🇬",
  "Costa Rica": "🇨🇷",
  "Croatia": "🇭🇷",
  "Cuba": "🇨🇺",
  "Cyprus": "🇨🇾",
  "Czech Republic": "🇨🇿",
  "Denmark": "🇩🇰",
  "Djibouti": "🇩🇯",
  "Dominica": "🇩🇲",
  "Dominican Republic": "🇩🇴",
  "DR Congo": "🇨🇩",
  "Ecuador": "🇪🇨",
  "Egypt": "🇪🇬",
  "El Salvador": "🇸🇻",
  "Equatorial Guinea": "🇬🇶",
  "Eritrea": "🇪🇷",
  "Estonia": "🇪🇪",
  "Eswatini": "🇸🇿",
  "Ethiopia": "🇪🇹",
  "Fiji": "🇫🇯",
  "Finland": "🇫🇮",
  "France": "🇫🇷",
  "Gabon": "🇬🇦",
  "Gambia": "🇬🇲",
  "Georgia": "🇬🇪",
  "Germany": "🇩🇪",
  "Ghana": "🇬🇭",
  "Greece": "🇬🇷",
  "Grenada": "🇬🇩",
  "Guatemala": "🇬🇹",
  "Guinea": "🇬🇳",
  "Guinea-Bissau": "🇬🇼",
  "Guyana": "🇬🇾",
  "Haiti": "🇭🇹",
  "Honduras": "🇭🇳",
  "Hungary": "🇭🇺",
  "Iceland": "🇮🇸",
  "India": "🇮🇳",
  "Indonesia": "🇮🇩",
  "Iran": "🇮🇷",
  "Iraq": "🇮🇶",
  "Ireland": "🇮🇪",
  "Israel": "🇮🇱",
  "Italy": "🇮🇹",
  "Ivory Coast": "🇨🇮",
  "Jamaica": "🇯🇲",
  "Japan": "🇯🇵",
  "Jordan": "🇯🇴",
  "Kazakhstan": "🇰🇿",
  "Kenya": "🇰🇪",
  "Kiribati": "🇰🇮",
  "Kosovo": "🇽🇰",
  "Kuwait": "🇰🇼",
  "Kyrgyzstan": "🇰🇬",
  "Laos": "🇱🇦",
  "Latvia": "🇱🇻",
  "Lebanon": "🇱🇧",
  "Lesotho": "🇱🇸",
  "Liberia": "🇱🇷",
  "Libya": "🇱🇾",
  "Liechtenstein": "🇱🇮",
  "Lithuania": "🇱🇹",
  "Luxembourg": "🇱🇺",
  "Madagascar": "🇲🇬",
  "Malawi": "🇲🇼",
  "Malaysia": "🇲🇾",
  "Maldives": "🇲🇻",
  "Mali": "🇲🇱",
  "Malta": "🇲🇹",
  "Marshall Islands": "🇲🇭",
  "Mauritania": "🇲🇷",
  "Mauritius": "🇲🇺",
  "Mexico": "🇲🇽",
  "Micronesia": "🇫🇲",
  "Moldova": "🇲🇩",
  "Monaco": "🇲🇨",
  "Mongolia": "🇲🇳",
  "Montenegro": "🇲🇪",
  "Morocco": "🇲🇦",
  "Mozambique": "🇲🇿",
  "Myanmar": "🇲🇲",
  "Namibia": "🇳🇦",
  "Nauru": "🇳🇷",
  "Nepal": "🇳🇵",
  "Netherlands": "🇳🇱",
  "New Zealand": "🇳🇿",
  "Nicaragua": "🇳🇮",
  "Niger": "🇳🇪",
  "Nigeria": "🇳🇬",
  "North Korea": "🇰🇵",
  "North Macedonia": "🇲🇰",
  "Norway": "🇳🇴",
  "Oman": "🇴🇲",
  "Pakistan": "🇵🇰",
  "Palau": "🇵🇼",
  "Palestine": "🇵🇸",
  "Panama": "🇵🇦",
  "Papua New Guinea": "🇵🇬",
  "Paraguay": "🇵🇾",
  "Peru": "🇵🇪",
  "Philippines": "🇵🇭",
  "Poland": "🇵🇱",
  "Portugal": "🇵🇹",
  "Qatar": "🇶🇦",
  "Romania": "🇷🇴",
  "Russia": "🇷🇺",
  "Rwanda": "🇷🇼",
  "Saint Kitts and Nevis": "🇰🇳",
  "Saint Lucia": "🇱🇨",
  "Saint Vincent and the Grenadines": "🇻🇨",
  "Samoa": "🇼🇸",
  "San Marino": "🇸🇲",
  "Sao Tome and Principe": "🇸🇹",
  "Saudi Arabia": "🇸🇦",
  "Senegal": "🇸🇳",
  "Serbia": "🇷🇸",
  "Seychelles": "🇸🇨",
  "Sierra Leone": "🇸🇱",
  "Singapore": "🇸🇬",
  "Slovakia": "🇸🇰",
  "Slovenia": "🇸🇮",
  "Solomon Islands": "🇸🇧",
  "Somalia": "🇸🇴",
  "South Africa": "🇿🇦",
  "South Korea": "🇰🇷",
  "South Sudan": "🇸🇸",
  "Spain": "🇪🇸",
  "Sri Lanka": "🇱🇰",
  "Sudan": "🇸🇩",
  "Suriname": "🇸🇷",
  "Sweden": "🇸🇪",
  "Switzerland": "🇨🇭",
  "Syria": "🇸🇾",
  "Taiwan": "🇹🇼",
  "Tajikistan": "🇹🇯",
  "Tanzania": "🇹🇿",
  "Thailand": "🇹🇭",
  "Timor-Leste": "🇹🇱",
  "Togo": "🇹🇬",
  "Tonga": "🇹🇴",
  "Trinidad and Tobago": "🇹🇹",
  "Tunisia": "🇹🇳",
  "Turkey": "🇹🇷",
  "Turkmenistan": "🇹🇲",
  "Tuvalu": "🇹🇻",
  "Uganda": "🇺🇬",
  "Ukraine": "🇺🇦",
  "United Arab Emirates": "🇦🇪",
  "United Kingdom": "🇬🇧",
  "United States": "🇺🇸",
  "Uruguay": "🇺🇾",
  "Uzbekistan": "🇺🇿",
  "Vanuatu": "🇻🇺",
  "Vatican City": "🇻🇦",
  "Venezuela": "🇻🇪",
  "Vietnam": "🇻🇳",
  "Yemen": "🇾🇪",
  "Zambia": "🇿🇲",
  "Zimbabwe": "🇿🇼",
};

// Code to country name and flag mapping
const codeToCountry: Record<string, { name: string; flag: string }> = {
  "AF": { name: "Afghanistan", flag: "🇦🇫" },
  "AL": { name: "Albania", flag: "🇦🇱" },
  "DZ": { name: "Algeria", flag: "🇩🇿" },
  "AD": { name: "Andorra", flag: "🇦🇩" },
  "AO": { name: "Angola", flag: "🇦🇴" },
  "AG": { name: "Antigua and Barbuda", flag: "🇦🇬" },
  "AR": { name: "Argentina", flag: "🇦🇷" },
  "AM": { name: "Armenia", flag: "🇦🇲" },
  "AU": { name: "Australia", flag: "🇦🇺" },
  "AT": { name: "Austria", flag: "🇦🇹" },
  "AZ": { name: "Azerbaijan", flag: "🇦🇿" },
  "BS": { name: "Bahamas", flag: "🇧🇸" },
  "BH": { name: "Bahrain", flag: "🇧🇭" },
  "BD": { name: "Bangladesh", flag: "🇧🇩" },
  "BB": { name: "Barbados", flag: "🇧🇧" },
  "BY": { name: "Belarus", flag: "🇧🇾" },
  "BE": { name: "Belgium", flag: "🇧🇪" },
  "BZ": { name: "Belize", flag: "🇧🇿" },
  "BJ": { name: "Benin", flag: "🇧🇯" },
  "BT": { name: "Bhutan", flag: "🇧🇹" },
  "BO": { name: "Bolivia", flag: "🇧🇴" },
  "BA": { name: "Bosnia and Herzegovina", flag: "🇧🇦" },
  "BW": { name: "Botswana", flag: "🇧🇼" },
  "BR": { name: "Brazil", flag: "🇧🇷" },
  "BN": { name: "Brunei", flag: "🇧🇳" },
  "BG": { name: "Bulgaria", flag: "🇧🇬" },
  "BF": { name: "Burkina Faso", flag: "🇧🇫" },
  "BI": { name: "Burundi", flag: "🇧🇮" },
  "KH": { name: "Cambodia", flag: "🇰🇭" },
  "CM": { name: "Cameroon", flag: "🇨🇲" },
  "CA": { name: "Canada", flag: "🇨🇦" },
  "CV": { name: "Cape Verde", flag: "🇨🇻" },
  "CF": { name: "Central African Republic", flag: "🇨🇫" },
  "TD": { name: "Chad", flag: "🇹🇩" },
  "CL": { name: "Chile", flag: "🇨🇱" },
  "CN": { name: "China", flag: "🇨🇳" },
  "CO": { name: "Colombia", flag: "🇨🇴" },
  "KM": { name: "Comoros", flag: "🇰🇲" },
  "CG": { name: "Congo", flag: "🇨🇬" },
  "CR": { name: "Costa Rica", flag: "🇨🇷" },
  "HR": { name: "Croatia", flag: "🇭🇷" },
  "CU": { name: "Cuba", flag: "🇨🇺" },
  "CY": { name: "Cyprus", flag: "🇨🇾" },
  "CZ": { name: "Czech Republic", flag: "🇨🇿" },
  "DK": { name: "Denmark", flag: "🇩🇰" },
  "DJ": { name: "Djibouti", flag: "🇩🇯" },
  "DM": { name: "Dominica", flag: "🇩🇲" },
  "DO": { name: "Dominican Republic", flag: "🇩🇴" },
  "CD": { name: "DR Congo", flag: "🇨🇩" },
  "EC": { name: "Ecuador", flag: "🇪🇨" },
  "EG": { name: "Egypt", flag: "🇪🇬" },
  "SV": { name: "El Salvador", flag: "🇸🇻" },
  "GQ": { name: "Equatorial Guinea", flag: "🇬🇶" },
  "ER": { name: "Eritrea", flag: "🇪🇷" },
  "EE": { name: "Estonia", flag: "🇪🇪" },
  "SZ": { name: "Eswatini", flag: "🇸🇿" },
  "ET": { name: "Ethiopia", flag: "🇪🇹" },
  "FJ": { name: "Fiji", flag: "🇫🇯" },
  "FI": { name: "Finland", flag: "🇫🇮" },
  "FR": { name: "France", flag: "🇫🇷" },
  "GA": { name: "Gabon", flag: "🇬🇦" },
  "GM": { name: "Gambia", flag: "🇬🇲" },
  "GE": { name: "Georgia", flag: "🇬🇪" },
  "DE": { name: "Germany", flag: "🇩🇪" },
  "GH": { name: "Ghana", flag: "🇬🇭" },
  "GR": { name: "Greece", flag: "🇬🇷" },
  "GD": { name: "Grenada", flag: "🇬🇩" },
  "GT": { name: "Guatemala", flag: "🇬🇹" },
  "GN": { name: "Guinea", flag: "🇬🇳" },
  "GW": { name: "Guinea-Bissau", flag: "🇬🇼" },
  "GY": { name: "Guyana", flag: "🇬🇾" },
  "HT": { name: "Haiti", flag: "🇭🇹" },
  "HN": { name: "Honduras", flag: "🇭🇳" },
  "HU": { name: "Hungary", flag: "🇭🇺" },
  "IS": { name: "Iceland", flag: "🇮🇸" },
  "IN": { name: "India", flag: "🇮🇳" },
  "ID": { name: "Indonesia", flag: "🇮🇩" },
  "IR": { name: "Iran", flag: "🇮🇷" },
  "IQ": { name: "Iraq", flag: "🇮🇶" },
  "IE": { name: "Ireland", flag: "🇮🇪" },
  "IL": { name: "Israel", flag: "🇮🇱" },
  "IT": { name: "Italy", flag: "🇮🇹" },
  "CI": { name: "Ivory Coast", flag: "🇨🇮" },
  "JM": { name: "Jamaica", flag: "🇯🇲" },
  "JP": { name: "Japan", flag: "🇯🇵" },
  "JO": { name: "Jordan", flag: "🇯🇴" },
  "KZ": { name: "Kazakhstan", flag: "🇰🇿" },
  "KE": { name: "Kenya", flag: "🇰🇪" },
  "KI": { name: "Kiribati", flag: "🇰🇮" },
  "XK": { name: "Kosovo", flag: "🇽🇰" },
  "KW": { name: "Kuwait", flag: "🇰🇼" },
  "KG": { name: "Kyrgyzstan", flag: "🇰🇬" },
  "LA": { name: "Laos", flag: "🇱🇦" },
  "LV": { name: "Latvia", flag: "🇱🇻" },
  "LB": { name: "Lebanon", flag: "🇱🇧" },
  "LS": { name: "Lesotho", flag: "🇱🇸" },
  "LR": { name: "Liberia", flag: "🇱🇷" },
  "LY": { name: "Libya", flag: "🇱🇾" },
  "LI": { name: "Liechtenstein", flag: "🇱🇮" },
  "LT": { name: "Lithuania", flag: "🇱🇹" },
  "LU": { name: "Luxembourg", flag: "🇱🇺" },
  "MG": { name: "Madagascar", flag: "🇲🇬" },
  "MW": { name: "Malawi", flag: "🇲🇼" },
  "MY": { name: "Malaysia", flag: "🇲🇾" },
  "MV": { name: "Maldives", flag: "🇲🇻" },
  "ML": { name: "Mali", flag: "🇲🇱" },
  "MT": { name: "Malta", flag: "🇲🇹" },
  "MH": { name: "Marshall Islands", flag: "🇲🇭" },
  "MR": { name: "Mauritania", flag: "🇲🇷" },
  "MU": { name: "Mauritius", flag: "🇲🇺" },
  "MX": { name: "Mexico", flag: "🇲🇽" },
  "FM": { name: "Micronesia", flag: "🇫🇲" },
  "MD": { name: "Moldova", flag: "🇲🇩" },
  "MC": { name: "Monaco", flag: "🇲🇨" },
  "MN": { name: "Mongolia", flag: "🇲🇳" },
  "ME": { name: "Montenegro", flag: "🇲🇪" },
  "MA": { name: "Morocco", flag: "🇲🇦" },
  "MZ": { name: "Mozambique", flag: "🇲🇿" },
  "MM": { name: "Myanmar", flag: "🇲🇲" },
  "NA": { name: "Namibia", flag: "🇳🇦" },
  "NR": { name: "Nauru", flag: "🇳🇷" },
  "NP": { name: "Nepal", flag: "🇳🇵" },
  "NL": { name: "Netherlands", flag: "🇳🇱" },
  "NZ": { name: "New Zealand", flag: "🇳🇿" },
  "NI": { name: "Nicaragua", flag: "🇳🇮" },
  "NE": { name: "Niger", flag: "🇳🇪" },
  "NG": { name: "Nigeria", flag: "🇳🇬" },
  "KP": { name: "North Korea", flag: "🇰🇵" },
  "MK": { name: "North Macedonia", flag: "🇲🇰" },
  "NO": { name: "Norway", flag: "🇳🇴" },
  "OM": { name: "Oman", flag: "🇴🇲" },
  "PK": { name: "Pakistan", flag: "🇵🇰" },
  "PW": { name: "Palau", flag: "🇵🇼" },
  "PS": { name: "Palestine", flag: "🇵🇸" },
  "PA": { name: "Panama", flag: "🇵🇦" },
  "PG": { name: "Papua New Guinea", flag: "🇵🇬" },
  "PY": { name: "Paraguay", flag: "🇵🇾" },
  "PE": { name: "Peru", flag: "🇵🇪" },
  "PH": { name: "Philippines", flag: "🇵🇭" },
  "PL": { name: "Poland", flag: "🇵🇱" },
  "PT": { name: "Portugal", flag: "🇵🇹" },
  "QA": { name: "Qatar", flag: "🇶🇦" },
  "RO": { name: "Romania", flag: "🇷🇴" },
  "RU": { name: "Russia", flag: "🇷🇺" },
  "RW": { name: "Rwanda", flag: "🇷🇼" },
  "KN": { name: "Saint Kitts and Nevis", flag: "🇰🇳" },
  "LC": { name: "Saint Lucia", flag: "🇱🇨" },
  "VC": { name: "Saint Vincent and the Grenadines", flag: "🇻🇨" },
  "WS": { name: "Samoa", flag: "🇼🇸" },
  "SM": { name: "San Marino", flag: "🇸🇲" },
  "ST": { name: "Sao Tome and Principe", flag: "🇸🇹" },
  "SA": { name: "Saudi Arabia", flag: "🇸🇦" },
  "SN": { name: "Senegal", flag: "🇸🇳" },
  "RS": { name: "Serbia", flag: "🇷🇸" },
  "SC": { name: "Seychelles", flag: "🇸🇨" },
  "SL": { name: "Sierra Leone", flag: "🇸🇱" },
  "SG": { name: "Singapore", flag: "🇸🇬" },
  "SK": { name: "Slovakia", flag: "🇸🇰" },
  "SI": { name: "Slovenia", flag: "🇸🇮" },
  "SB": { name: "Solomon Islands", flag: "🇸🇧" },
  "SO": { name: "Somalia", flag: "🇸🇴" },
  "ZA": { name: "South Africa", flag: "🇿🇦" },
  "KR": { name: "South Korea", flag: "🇰🇷" },
  "SS": { name: "South Sudan", flag: "🇸🇸" },
  "ES": { name: "Spain", flag: "🇪🇸" },
  "LK": { name: "Sri Lanka", flag: "🇱🇰" },
  "SD": { name: "Sudan", flag: "🇸🇩" },
  "SR": { name: "Suriname", flag: "🇸🇷" },
  "SE": { name: "Sweden", flag: "🇸🇪" },
  "CH": { name: "Switzerland", flag: "🇨🇭" },
  "SY": { name: "Syria", flag: "🇸🇾" },
  "TW": { name: "Taiwan", flag: "🇹🇼" },
  "TJ": { name: "Tajikistan", flag: "🇹🇯" },
  "TZ": { name: "Tanzania", flag: "🇹🇿" },
  "TH": { name: "Thailand", flag: "🇹🇭" },
  "TL": { name: "Timor-Leste", flag: "🇹🇱" },
  "TG": { name: "Togo", flag: "🇹🇬" },
  "TO": { name: "Tonga", flag: "🇹🇴" },
  "TT": { name: "Trinidad and Tobago", flag: "🇹🇹" },
  "TN": { name: "Tunisia", flag: "🇹🇳" },
  "TR": { name: "Turkey", flag: "🇹🇷" },
  "TM": { name: "Turkmenistan", flag: "🇹🇲" },
  "TV": { name: "Tuvalu", flag: "🇹🇻" },
  "UG": { name: "Uganda", flag: "🇺🇬" },
  "UA": { name: "Ukraine", flag: "🇺🇦" },
  "AE": { name: "United Arab Emirates", flag: "🇦🇪" },
  "GB": { name: "United Kingdom", flag: "🇬🇧" },
  "US": { name: "United States", flag: "🇺🇸" },
  "UY": { name: "Uruguay", flag: "🇺🇾" },
  "UZ": { name: "Uzbekistan", flag: "🇺🇿" },
  "VU": { name: "Vanuatu", flag: "🇻🇺" },
  "VA": { name: "Vatican City", flag: "🇻🇦" },
  "VE": { name: "Venezuela", flag: "🇻🇪" },
  "VN": { name: "Vietnam", flag: "🇻🇳" },
  "YE": { name: "Yemen", flag: "🇾🇪" },
  "ZM": { name: "Zambia", flag: "🇿🇲" },
  "ZW": { name: "Zimbabwe", flag: "🇿🇼" },
};

// Alternative country name mappings (including diacritics and variations)
const alternativeNames: Record<string, string> = {
  "România": "Romania",
  "Румыния": "Romania",
  "Румунія": "Ukraine",
  "Deutschland": "Germany",
  "Allemagne": "Germany",
  "España": "Spain",
  "Espagne": "Spain",
  "Italia": "Italy",
  "Italie": "Italy",
  "Polska": "Poland",
  "Pologne": "Poland",
  "Česko": "Czech Republic",
  "Czechia": "Czech Republic",
  "Magyarország": "Hungary",
  "Hongrie": "Hungary",
  "Ελλάδα": "Greece",
  "Grèce": "Greece",
  "Türkiye": "Turkey",
  "Turquie": "Turkey",
  "Россия": "Russia",
  "Russie": "Russia",
  "日本": "Japan",
  "中国": "China",
  "한국": "South Korea",
  "Brasil": "Brazil",
  "Brésil": "Brazil",
  "Österreich": "Austria",
  "Autriche": "Austria",
  "Schweiz": "Switzerland",
  "Suisse": "Switzerland",
  "Belgique": "Belgium",
  "België": "Belgium",
  "Nederland": "Netherlands",
  "Pays-Bas": "Netherlands",
  "Sverige": "Sweden",
  "Suède": "Sweden",
  "Norge": "Norway",
  "Norvège": "Norway",
  "Danmark": "Denmark",
  "Danemark": "Denmark",
  "Suomi": "Finland",
  "Finlande": "Finland",
  "Ísland": "Iceland",
  "Islande": "Iceland",
  "Éire": "Ireland",
  "Irlande": "Ireland",
  "Україна": "Ukraine",
  "Беларусь": "Belarus",
  "Biélorussie": "Belarus",
  "Србија": "Serbia",
  "Serbie": "Serbia",
  "Hrvatska": "Croatia",
  "Croatie": "Croatia",
  "Slovenija": "Slovenia",
  "Slovénie": "Slovenia",
  "Slovensko": "Slovakia",
  "Slovaquie": "Slovakia",
  "България": "Bulgaria",
  "Bulgarie": "Bulgaria",
  "Ρουμανία": "Romania",
  "Roumanie": "Romania",
  "UK": "United Kingdom",
  "USA": "United States",
  "UAE": "United Arab Emirates",
};

/**
 * Normalize string for diacritic-insensitive comparison
 */
const normalizeString = (str: string) => 
  str.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase();

/**
 * Get the standardized country name from any input (code, local name, etc.)
 * @param country - Country name, code, or local name
 * @returns Standardized English country name
 */
export const getCountryName = (country: string | null | undefined): string => {
  if (!country) return "";
  
  // Check if it's a country code (2 letters uppercase)
  const upperCode = country.toUpperCase();
  if (codeToCountry[upperCode]) {
    return codeToCountry[upperCode].name;
  }
  
  // Check alternative names
  if (alternativeNames[country]) {
    return alternativeNames[country];
  }
  
  // Check if it's already a standard country name
  if (countryFlags[country]) {
    return country;
  }
  
  // Try diacritic-insensitive match for country names
  const normalizedInput = normalizeString(country);
  for (const name of Object.keys(countryFlags)) {
    if (normalizeString(name) === normalizedInput) {
      return name;
    }
  }
  
  // Try diacritic-insensitive match for alternative names
  for (const [altName, standardName] of Object.entries(alternativeNames)) {
    if (normalizeString(altName) === normalizedInput) {
      return standardName;
    }
  }
  
  // Return original if no match found
  return country;
};

/**
 * Get flag emoji for a country name or code
 * @param country - Country name or 2-letter code
 * @returns Flag emoji or null if not found
 */
export const getCountryFlag = (country: string | null | undefined): string | null => {
  if (!country) return null;
  
  // Check if it's a country code
  const upperCode = country.toUpperCase();
  if (codeToCountry[upperCode]) {
    return codeToCountry[upperCode].flag;
  }
  
  // Try direct name match first
  if (countryFlags[country]) {
    return countryFlags[country];
  }
  
  // Check alternative names
  if (alternativeNames[country]) {
    return countryFlags[alternativeNames[country]];
  }
  
  // Try diacritic-insensitive name match
  const normalizedInput = normalizeString(country);
  for (const [name, flag] of Object.entries(countryFlags)) {
    if (normalizeString(name) === normalizedInput) {
      return flag;
    }
  }
  
  // Try diacritic-insensitive match for alternative names
  for (const [altName, standardName] of Object.entries(alternativeNames)) {
    if (normalizeString(altName) === normalizedInput) {
      return countryFlags[standardName];
    }
  }
  
  return null;
};

/**
 * Get both flag and name for display
 * @param country - Country name or 2-letter code
 * @returns Object with flag and name
 */
export const getCountryDisplay = (country: string | null | undefined): { flag: string | null; name: string } => {
  return {
    flag: getCountryFlag(country),
    name: getCountryName(country),
  };
};
