// Maps country names to their local currency codes
const COUNTRY_CURRENCIES: Record<string, string> = {
  "România": "RON",
  "Romania": "RON",
  "Moldova": "MDL",
  "United States": "USD",
  "United Kingdom": "GBP",
  "Germany": "EUR",
  "France": "EUR",
  "Italy": "EUR",
  "Spain": "EUR",
  "Netherlands": "EUR",
  "Belgium": "EUR",
  "Austria": "EUR",
  "Portugal": "EUR",
  "Greece": "EUR",
  "Ireland": "EUR",
  "Finland": "EUR",
  "Slovakia": "EUR",
  "Slovenia": "EUR",
  "Estonia": "EUR",
  "Latvia": "EUR",
  "Lithuania": "EUR",
  "Luxembourg": "EUR",
  "Malta": "EUR",
  "Cyprus": "EUR",
  "Croatia": "EUR",
  "Poland": "PLN",
  "Czech Republic": "CZK",
  "Hungary": "HUF",
  "Sweden": "SEK",
  "Denmark": "DKK",
  "Norway": "NOK",
  "Switzerland": "CHF",
  "Turkey": "TRY",
  "Japan": "JPY",
  "China": "CNY",
  "South Korea": "KRW",
  "India": "INR",
  "Brazil": "BRL",
  "Canada": "CAD",
  "Australia": "AUD",
  "New Zealand": "NZD",
  "Mexico": "MXN",
  "Argentina": "ARS",
  "Colombia": "COP",
  "Chile": "CLP",
  "Russia": "RUB",
  "Ukraine": "UAH",
  "Bulgaria": "BGN",
  "Serbia": "RSD",
  "Israel": "ILS",
  "South Africa": "ZAR",
  "Egypt": "EGP",
  "Nigeria": "NGN",
  "Kenya": "KES",
  "Thailand": "THB",
  "Vietnam": "VND",
  "Philippines": "PHP",
  "Indonesia": "IDR",
  "Malaysia": "MYR",
  "Singapore": "SGD",
  "Taiwan": "TWD",
  "Hong Kong": "HKD",
  "United Arab Emirates": "AED",
  "Saudi Arabia": "SAR",
  "Qatar": "QAR",
  "Kuwait": "KWD",
  "Pakistan": "PKR",
  "Bangladesh": "BDT",
  "Sri Lanka": "LKR",
  "Morocco": "MAD",
  "Tunisia": "TND",
  "Algeria": "DZD",
  "Peru": "PEN",
  "Ecuador": "USD",
  "Venezuela": "VES",
  "Uruguay": "UYU",
  "Paraguay": "PYG",
  "Bolivia": "BOB",
  "Dominican Republic": "DOP",
  "Costa Rica": "CRC",
  "Panama": "PAB",
  "Jamaica": "JMD",
  "Iceland": "ISK",
  "Georgia": "GEL",
  "Armenia": "AMD",
  "Azerbaijan": "AZN",
  "Kazakhstan": "KZT",
  "Uzbekistan": "UZS",
};

export function getCurrencyForCountry(country: string | null | undefined): string {
  if (!country) return "EUR";
  return COUNTRY_CURRENCIES[country] || "EUR";
}
