// Common live music event types
export const EVENT_TYPES = [
  "Wedding",
  "Engagement",
  "Baptism",
  "Funeral",
  "Birthday Party",
  "Anniversary",
  "Graduation",
  "Prom",
  "Bachelor / Bachelorette Party",
  "Corporate Event",
  "Conference",
  "Product Launch",
  "Gala / Award Ceremony",
  "Charity / Fundraiser",
  "Private Party",
  "House Party",
  "Restaurant / Bar",
  "Club / Nightclub",
  "Concert",
  "Festival",
  "Cultural Event",
  "Religious Service",
  "School Event",
  "Holiday / Christmas Party",
  "New Year's Eve",
  "Easter Event",
  "Fashion Show",
  "Wine / Beer Tasting",
  "Cruise / Yacht Party",
  "Hotel / Resort Event",
  "Brand Activation",
  "TV / Film Production",
  "Studio Recording",
  "Other",
] as const;

export type EventType = typeof EVENT_TYPES[number];
