// Comprehensive list of world languages for the language picker.
// `code` is the BCP-47 / ISO 639-1 (or 639-3 fallback) code used by i18n.
export interface WorldLanguage {
  code: string;
  label: string; // native name
  english: string; // english name (for search)
  flag: string;
}

export const WORLD_LANGUAGES: WorldLanguage[] = [
  { code: "en", label: "English", english: "English", flag: "🇬🇧" },
  { code: "ro", label: "Română", english: "Romanian", flag: "🇷🇴" },
  { code: "fr", label: "Français", english: "French", flag: "🇫🇷" },
  { code: "de", label: "Deutsch", english: "German", flag: "🇩🇪" },
  { code: "es", label: "Español", english: "Spanish", flag: "🇪🇸" },
  { code: "it", label: "Italiano", english: "Italian", flag: "🇮🇹" },
  { code: "pt", label: "Português", english: "Portuguese", flag: "🇵🇹" },
  { code: "pt-BR", label: "Português (Brasil)", english: "Portuguese (Brazil)", flag: "🇧🇷" },
  { code: "nl", label: "Nederlands", english: "Dutch", flag: "🇳🇱" },
  { code: "pl", label: "Polski", english: "Polish", flag: "🇵🇱" },
  { code: "hu", label: "Magyar", english: "Hungarian", flag: "🇭🇺" },
  { code: "cs", label: "Čeština", english: "Czech", flag: "🇨🇿" },
  { code: "sk", label: "Slovenčina", english: "Slovak", flag: "🇸🇰" },
  { code: "sl", label: "Slovenščina", english: "Slovenian", flag: "🇸🇮" },
  { code: "hr", label: "Hrvatski", english: "Croatian", flag: "🇭🇷" },
  { code: "sr", label: "Српски", english: "Serbian", flag: "🇷🇸" },
  { code: "bs", label: "Bosanski", english: "Bosnian", flag: "🇧🇦" },
  { code: "mk", label: "Македонски", english: "Macedonian", flag: "🇲🇰" },
  { code: "sq", label: "Shqip", english: "Albanian", flag: "🇦🇱" },
  { code: "bg", label: "Български", english: "Bulgarian", flag: "🇧🇬" },
  { code: "el", label: "Ελληνικά", english: "Greek", flag: "🇬🇷" },
  { code: "tr", label: "Türkçe", english: "Turkish", flag: "🇹🇷" },
  { code: "uk", label: "Українська", english: "Ukrainian", flag: "🇺🇦" },
  { code: "ru", label: "Русский", english: "Russian", flag: "🇷🇺" },
  { code: "be", label: "Беларуская", english: "Belarusian", flag: "🇧🇾" },
  { code: "lt", label: "Lietuvių", english: "Lithuanian", flag: "🇱🇹" },
  { code: "lv", label: "Latviešu", english: "Latvian", flag: "🇱🇻" },
  { code: "et", label: "Eesti", english: "Estonian", flag: "🇪🇪" },
  { code: "fi", label: "Suomi", english: "Finnish", flag: "🇫🇮" },
  { code: "sv", label: "Svenska", english: "Swedish", flag: "🇸🇪" },
  { code: "no", label: "Norsk", english: "Norwegian", flag: "🇳🇴" },
  { code: "da", label: "Dansk", english: "Danish", flag: "🇩🇰" },
  { code: "is", label: "Íslenska", english: "Icelandic", flag: "🇮🇸" },
  { code: "ga", label: "Gaeilge", english: "Irish", flag: "🇮🇪" },
  { code: "cy", label: "Cymraeg", english: "Welsh", flag: "🏴󠁧󠁢󠁷󠁬󠁳󠁿" },
  { code: "gd", label: "Gàidhlig", english: "Scottish Gaelic", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿" },
  { code: "eu", label: "Euskara", english: "Basque", flag: "🇪🇸" },
  { code: "ca", label: "Català", english: "Catalan", flag: "🇪🇸" },
  { code: "gl", label: "Galego", english: "Galician", flag: "🇪🇸" },
  { code: "mt", label: "Malti", english: "Maltese", flag: "🇲🇹" },
  { code: "lb", label: "Lëtzebuergesch", english: "Luxembourgish", flag: "🇱🇺" },
  { code: "ar", label: "العربية", english: "Arabic", flag: "🇸🇦" },
  { code: "he", label: "עברית", english: "Hebrew", flag: "🇮🇱" },
  { code: "fa", label: "فارسی", english: "Persian", flag: "🇮🇷" },
  { code: "ps", label: "پښتو", english: "Pashto", flag: "🇦🇫" },
  { code: "ur", label: "اردو", english: "Urdu", flag: "🇵🇰" },
  { code: "hi", label: "हिन्दी", english: "Hindi", flag: "🇮🇳" },
  { code: "bn", label: "বাংলা", english: "Bengali", flag: "🇧🇩" },
  { code: "pa", label: "ਪੰਜਾਬੀ", english: "Punjabi", flag: "🇮🇳" },
  { code: "gu", label: "ગુજરાતી", english: "Gujarati", flag: "🇮🇳" },
  { code: "mr", label: "मराठी", english: "Marathi", flag: "🇮🇳" },
  { code: "ta", label: "தமிழ்", english: "Tamil", flag: "🇮🇳" },
  { code: "te", label: "తెలుగు", english: "Telugu", flag: "🇮🇳" },
  { code: "kn", label: "ಕನ್ನಡ", english: "Kannada", flag: "🇮🇳" },
  { code: "ml", label: "മലയാളം", english: "Malayalam", flag: "🇮🇳" },
  { code: "or", label: "ଓଡ଼ିଆ", english: "Odia", flag: "🇮🇳" },
  { code: "as", label: "অসমীয়া", english: "Assamese", flag: "🇮🇳" },
  { code: "ne", label: "नेपाली", english: "Nepali", flag: "🇳🇵" },
  { code: "si", label: "සිංහල", english: "Sinhala", flag: "🇱🇰" },
  { code: "my", label: "မြန်မာ", english: "Burmese", flag: "🇲🇲" },
  { code: "km", label: "ខ្មែរ", english: "Khmer", flag: "🇰🇭" },
  { code: "lo", label: "ລາວ", english: "Lao", flag: "🇱🇦" },
  { code: "th", label: "ไทย", english: "Thai", flag: "🇹🇭" },
  { code: "vi", label: "Tiếng Việt", english: "Vietnamese", flag: "🇻🇳" },
  { code: "id", label: "Bahasa Indonesia", english: "Indonesian", flag: "🇮🇩" },
  { code: "ms", label: "Bahasa Melayu", english: "Malay", flag: "🇲🇾" },
  { code: "tl", label: "Tagalog", english: "Tagalog", flag: "🇵🇭" },
  { code: "zh", label: "中文 (简体)", english: "Chinese (Simplified)", flag: "🇨🇳" },
  { code: "zh-TW", label: "中文 (繁體)", english: "Chinese (Traditional)", flag: "🇹🇼" },
  { code: "ja", label: "日本語", english: "Japanese", flag: "🇯🇵" },
  { code: "ko", label: "한국어", english: "Korean", flag: "🇰🇷" },
  { code: "mn", label: "Монгол", english: "Mongolian", flag: "🇲🇳" },
  { code: "kk", label: "Қазақша", english: "Kazakh", flag: "🇰🇿" },
  { code: "ky", label: "Кыргызча", english: "Kyrgyz", flag: "🇰🇬" },
  { code: "uz", label: "Oʻzbekcha", english: "Uzbek", flag: "🇺🇿" },
  { code: "tg", label: "Тоҷикӣ", english: "Tajik", flag: "🇹🇯" },
  { code: "tk", label: "Türkmençe", english: "Turkmen", flag: "🇹🇲" },
  { code: "az", label: "Azərbaycan", english: "Azerbaijani", flag: "🇦🇿" },
  { code: "hy", label: "Հայերեն", english: "Armenian", flag: "🇦🇲" },
  { code: "ka", label: "ქართული", english: "Georgian", flag: "🇬🇪" },
  { code: "ku", label: "Kurdî", english: "Kurdish", flag: "🇮🇶" },
  { code: "sw", label: "Kiswahili", english: "Swahili", flag: "🇰🇪" },
  { code: "am", label: "አማርኛ", english: "Amharic", flag: "🇪🇹" },
  { code: "ti", label: "ትግርኛ", english: "Tigrinya", flag: "🇪🇷" },
  { code: "so", label: "Soomaali", english: "Somali", flag: "🇸🇴" },
  { code: "ha", label: "Hausa", english: "Hausa", flag: "🇳🇬" },
  { code: "yo", label: "Yorùbá", english: "Yoruba", flag: "🇳🇬" },
  { code: "ig", label: "Igbo", english: "Igbo", flag: "🇳🇬" },
  { code: "zu", label: "isiZulu", english: "Zulu", flag: "🇿🇦" },
  { code: "xh", label: "isiXhosa", english: "Xhosa", flag: "🇿🇦" },
  { code: "af", label: "Afrikaans", english: "Afrikaans", flag: "🇿🇦" },
  { code: "st", label: "Sesotho", english: "Sesotho", flag: "🇱🇸" },
  { code: "sn", label: "ChiShona", english: "Shona", flag: "🇿🇼" },
  { code: "rw", label: "Kinyarwanda", english: "Kinyarwanda", flag: "🇷🇼" },
  { code: "mg", label: "Malagasy", english: "Malagasy", flag: "🇲🇬" },
  { code: "ht", label: "Kreyòl Ayisyen", english: "Haitian Creole", flag: "🇭🇹" },
  { code: "haw", label: "ʻŌlelo Hawaiʻi", english: "Hawaiian", flag: "🇺🇸" },
  { code: "mi", label: "Te Reo Māori", english: "Maori", flag: "🇳🇿" },
  { code: "sm", label: "Gagana Samoa", english: "Samoan", flag: "🇼🇸" },
  { code: "to", label: "Lea Faka-Tonga", english: "Tongan", flag: "🇹🇴" },
  { code: "fj", label: "Vosa Vakaviti", english: "Fijian", flag: "🇫🇯" },
  { code: "eo", label: "Esperanto", english: "Esperanto", flag: "🌐" },
  { code: "la", label: "Latina", english: "Latin", flag: "🇻🇦" },
  { code: "yi", label: "ייִדיש", english: "Yiddish", flag: "🇮🇱" },
  { code: "fo", label: "Føroyskt", english: "Faroese", flag: "🇫🇴" },
  { code: "kl", label: "Kalaallisut", english: "Greenlandic", flag: "🇬🇱" },
  { code: "se", label: "Davvisámegiella", english: "Northern Sami", flag: "🇳🇴" },
  { code: "br", label: "Brezhoneg", english: "Breton", flag: "🇫🇷" },
  { code: "co", label: "Corsu", english: "Corsican", flag: "🇫🇷" },
  { code: "oc", label: "Occitan", english: "Occitan", flag: "🇫🇷" },
  { code: "rm", label: "Rumantsch", english: "Romansh", flag: "🇨🇭" },
  { code: "fy", label: "Frysk", english: "Frisian", flag: "🇳🇱" },
  { code: "dv", label: "ދިވެހި", english: "Dhivehi", flag: "🇲🇻" },
  { code: "bo", label: "བོད་སྐད་", english: "Tibetan", flag: "🇨🇳" },
  { code: "ug", label: "ئۇيغۇرچە", english: "Uyghur", flag: "🇨🇳" },
];
