project_id = "ccdgoduekpiesdmkluff"

[functions.stripe-webhook]
verify_jwt = false

[functions.upload-artist-avatar]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false
